spring:
  application:
    name: prometheus-test-app
  liquibase:
    enabled: false

aspects:
  trace-call-stack:
    package-search-prefixes: test.prometheus
    clean-cglib-prefixes-in-class-names: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/management"
      path-mapping:
        health: "health-endpoint-v3-228"
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true

info:
  chto-to_vaznoe:
    my-honest-opinion: "None"